### ISSUE TITLE
Build fails when ACL is not enabled

### ISSUE THREAD

**Issue by justablob** [sfjro/aufs-standalone#16]
Hello,

we have observed a build failure when FS ACLs are not enabled in the kernel config.
The issue was fixed by modifying line 444 in `fs/aufs/fsctx.c`:
```
- au_ignore_flag("acl"),
+ au_ignore_flag("acl", Opt_ignore_silent),
```

**Comment by sfjro** [comment]
Hello Blobbo,

The Blobbo:
> we have observed a build failure when FS ACLs are not enabled in the kernel config.
> The issue was fixed by modifying line 444 in `fs/aufs/fsctx.c`:
> ```
> - au_ignore_flag("acl"),
> + au_ignore_flag("acl", Opt_ignore_silent),
> ```

Thanks for the report.
You are totally right.
That is my bonehead mistake.
I am going to release the fix on next Monday.


J. R. Okajima

**Comment by justablob** [comment]
Hey sjfro,

No biggie, it was simple enough to work around. I would've created a pull request but you have so many branches :p

Thanks in advance for the fix!

**Comment by justablob** [comment]
By the way, I'm just wondering, do you ever intend on mainlining aufs? It's more feature-rich than all other union/overlay filesystems I can find and I'd love to see it used more. For example, we're currently building an embedded system that relies on aufs for its package management and updating capabilities, where it's the only filesystem that includes all features we need.

**Comment by sfjro** [comment]
------- Blind-Carbon-Copy

From: "J. R. Okajima" ***@***.***>
To: ***@***.***
Subject: aufs5 GIT release
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-ID: ***@***.***>
Date: Mon, 06 Jun 2022 09:32:50 +0900
Message-ID: ***@***.***>

o bugfix
  When CONFIG_FS_POSIX_ACL is disabled, a syntax error in aufs code appears.
  Reported and fixed by The Blobbo.
  And I changed his patch just a little bit.

J. R. Okajima

- ----------------------------------------
- - aufs5-linux.git
      aufs: bugfix, syntax error when !CONFIG_FS_POSIX_ACL

- - aufs5-standalone.git#aufs5.10
  ditto

- - aufs-util.git
  nothing

------- End of Blind-Carbon-Copy

**Comment by sfjro** [comment]
The Blobbo:
> By the way, I'm just wondering, do you ever intend on mainlining aufs? It's more feature-rich than all other union/overlay filesystems I can find and I'd love to see it used more. For example, we're currently building an embedded system that relies on aufs for its package management and updating capabilities, where it's the only filesystem that includes all features we need.

Waoh, that reminds me an aufs history, also I am glad to know that aufs
is helping you.

Here I quote a part of aufs README file,
----------------------------------------
Note: it becomes clear that "Aufs was rejected. Let's give it up."
      According to Christoph Hellwig, linux rejects all union-type
      filesystems but UnionMount.
<http://marc.info/?l=linux-kernel&m=123938533724484&w=2>

PS. Al Viro seems have a plan to merge aufs as well as overlayfs and
    UnionMount, and he pointed out an issue around a directory mutex
    lock and aufs addressed it. But it is still unsure whether aufs will
    be merged (or any other union solution).
<http://marc.info/?l=linux-kernel&m=136312705029295&w=1>
----------------------------------------

Later, overlayfs was merged into mainline and many aufs users switched
to it.  But some users came back to aufs. The reason is very similar to
yours.
It was many years from now.


J. R. Okajima

**Comment by justablob** [comment]
sjfro,

Thank you for your replies and for the quick fix.

Also, I'm sad to hear aufs was rejected. Those messages you sent are from many years ago - any chance things would be different today?
