### ISSUE TITLE
6.0 repos

### ISSUE THREAD

**Issue by peabee** [sfjro/aufs-standalone#22]
@sfjro 
please see:
https://github.com/puppylinux-woof-CE/woof-CE/issues/3539#issuecomment-1288016378

This might assist?
Regards
PeeBee

**Comment by sfjro** [comment]
PB:
> please see:
> https://github.com/puppylinux-woof-CE/woof-CE/issues/3539#issuecomment-1288016378
>
> This might assist?

Unfotunately no,
I can create aufs6-standalone.git on github coz it has aufs files
only. git-pushing whole history is not a big deal.
The problem is aufs6-linux.git. I cannot fork torvalds/linux.git, so
even if I took the way your URL describes, I'd have to push whole
history of linux. I don't think it is a good idea.


J. R. Okajima

**Comment by dimkr** [comment]
> I don't think it is a good idea.

Due to bandwidth constraints?

**Comment by sfjro** [comment]
Dima Krasner:
> Due to bandwidth constraints?

Yes.


J. R. Okajima
